/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author MCJA
 */
public class VentanaEntradaProductos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEntradaProductos
     */
    public VentanaEntradaProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDatosProductos = new javax.swing.JLabel();
        jLabelNombreProducto = new javax.swing.JLabel();
        jLabelCaracteristicasEspecialesProductos = new javax.swing.JLabel();
        jLabelUnidad = new javax.swing.JLabel();
        jLabelPesoUnidad = new javax.swing.JLabel();
        txtNombProd = new javax.swing.JTextField();
        txtCaract = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabelVolumenUnidad = new javax.swing.JLabel();
        txtVolum = new javax.swing.JTextField();
        btnIngresarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDatosProductos.setText("Datos Productos");

        jLabelNombreProducto.setText("Nombre");

        jLabelCaracteristicasEspecialesProductos.setText("Caracteristicas Especiales");

        jLabelUnidad.setText("Unidad");

        jLabelPesoUnidad.setText("Peso por unidad");

        txtNombProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombProdActionPerformed(evt);
            }
        });

        jLabelVolumenUnidad.setText("Volumen por unidad");

        txtVolum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumActionPerformed(evt);
            }
        });

        btnIngresarProd.setText("Ingresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVolumenUnidad)
                    .addComponent(jLabelNombreProducto)
                    .addComponent(jLabelUnidad)
                    .addComponent(jLabelPesoUnidad)
                    .addComponent(jLabelCaracteristicasEspecialesProductos))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombProd)
                        .addComponent(txtCaract)
                        .addComponent(txtUnidad)
                        .addComponent(txtPeso)
                        .addComponent(txtVolum, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE))
                    .addComponent(jLabelDatosProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 654, Short.MAX_VALUE)
                .addComponent(btnIngresarProd)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDatosProductos)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreProducto))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCaract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCaracteristicasEspecialesProductos))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUnidad)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesoUnidad)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVolumenUnidad)
                    .addComponent(txtVolum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarProd)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombProdActionPerformed

    private void txtVolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEntradaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEntradaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIngresarProd;
    private javax.swing.JLabel jLabelCaracteristicasEspecialesProductos;
    private javax.swing.JLabel jLabelDatosProductos;
    private javax.swing.JLabel jLabelNombreProducto;
    private javax.swing.JLabel jLabelPesoUnidad;
    private javax.swing.JLabel jLabelUnidad;
    private javax.swing.JLabel jLabelVolumenUnidad;
    public javax.swing.JTextField txtCaract;
    public javax.swing.JTextField txtNombProd;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtUnidad;
    public javax.swing.JTextField txtVolum;
    // End of variables declaration//GEN-END:variables
}
